### ISSUE TITLE
No matching distribution found for django-templatetag-randomgen

### ISSUE THREAD

**Issue by bashu** [bkeating/django-templatetag-randomgen#2]
``` shell
$ pip install django-templatetag-randomgen
Collecting django-templatetag-randomgen
  Could not find a version that satisfies the requirement django-templatetag-randomgen (from versions: )
No matching distribution found for django-templatetag-randomgen
```

**Comment by bashu** [comment]
fixed, https://pypi.python.org/pypi/django-templatetag-randomgen

PS. ask me if you need access

**Comment by bkeating** [comment]
Nice. Thank you so much for submitting it for us. :)

How would we go about pushing updates? If we need access/permissions then I guess we should probably set those up now so we have them. You're otherwise welcome to push any updates yourself.

**Comment by bashu** [comment]
do you have account on pypi, if not create it and tell your username?
